### ISSUE TITLE
Add snip to return casing of a string

### ISSUE THREAD

**Issue by rahulrk-dev** [rahulrk-dev/snips#16]
The casings must include - 
- Uppercase
- Lowercase
- Sentence case
- Title

_optional, but great if included_ - 
- snake
- constant
- camel
- kebab
- pascal

**Comment by void-57** [comment]
@DevTMK I would like to work on it but can you explain more.

**Comment by subashpaul** [comment]
can i do it?

**Comment by DevTMK** [comment]
> @DevTMK I would like to work on it but can you explain more.

The snip/function should return the casing of input string
E.g. - checkCasing("HELLO WORLD") // Uppercase

**Comment by savi001** [comment]
Can u assign this to me , i can do better as earlier also i have worked for u .

**Comment by DevTMK** [comment]
Sure @savi001
